/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElTag: typeof import('element-plus/es')['ElTag']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconsIconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconsIconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconsIconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconsIconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconsIconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserComponents: typeof import('./src/components/user/userComponents.vue')['default']
  }
}
